HOME_PATH = "{path}/VOTEN"
DATA_PATH = "%s/Data" % HOME_PATH
RAWDATA_PATH = "%s/RawData" % DATA_PATH
DATASET_PATH = "%s/Datasets" % DATA_PATH
DOWNLOADS_PATH = "%s/Downloads" % DATA_PATH

TMP_PATH = "%s/Tmp" % HOME_PATH
MODEL_PATH = "%s/Saved" % DATA_PATH

KDC_RAWDATA_PATH = "%s/KDC" % RAWDATA_PATH
KDC_DATASET_PATH = "%s/KDC" % DATASET_PATH
CENSINCOME_RAWDATA_PATH = "%s/CENSINCOME" % RAWDATA_PATH
CENSINCOME_DATASET_PATH = "%s/CENSINCOME" % DATASET_PATH
COVTYPE_DATASET_PATH = "%s/COVTYPE" % DATASET_PATH
IJCAI18X_DATASET_PATH = "%s/IJCAI18X" % DATASET_PATH
IJCAI18X_RAWDATA_PATH = "%s/IJCAI18X" % RAWDATA_PATH
